### ISSUE TITLE
fehler

### ISSUE THREAD

**Issue by noawinDE** [Schleyer-EDV/blackhost_cp#1]
Seite bleibt weiß nach richtiger Installation

**Comment by bastianleicht** [comment]
Du musst in `app/functions` die `test.php` Class löschen. Danach funktioniert alles einwandfrei.

Oder du lädst einfach meinen gepatchten Fork herunter. 
https://github.com/bastianleicht/blackhost_cp/tree/patch-1

**Comment by BSchleyer** [comment]
Die test.php in den Functions habe ich im letzten Commit entfernt, daher einfach neu runterladen und aufsetzen. Dann sollte alles problemlos funktionieren.

Zusätzlich habe ich eben den PR von Bastian bestätigt bzw. gemerged.
