### ISSUE TITLE
Fehler beim kaufen eines Minecraft-Servers

### ISSUE THREAD

**Issue by GreenPepperYT** [Schleyer-EDV/blackhost_cp#4]
Hi, wenn ich mir einen Minecraft-Server kaufe kriege ich im Debug-Mode folgenden Bildschirm: 
https://prnt.sc/jeQPTvy7-7lW

Die Pterodactyl-Daten sind in der .env eingetragen und laut Pterodactyl wurde der Key auch erst eben genutzt.

**Comment by bastianleicht** [comment]
Sieht danach aus als ob ein API Call nicht durchgeführt werden kann, weil er nicht existiert.

**Comment by GreenPepperYT** [comment]
Inwiefern das Egg? Es sind die standard Pterodactyl Eggs installiert.

**Comment by bastianleicht** [comment]
Dann ist irgendwas falsch konfiguriert.

**Comment by bastianleicht** [comment]
Möglicherweise gibt es auch einen Fehler / eine andere Konfiguration im BH-Panel. Habe dort die Gameserver noch nicht getestet.

**Comment by bastianleicht** [comment]
Habe mich nochmal weiter mit deinem Screenshot beschäftigt.

https://github.com/Schleyer-EDV/blackhost_cp/blob/1b610a7dced3d7c31dcc6cd653bb48b8373acded/app/functions/Pterodactyl.php#L31

Hier wird ein Egg mit der Nest ID 2 abgerufen. Diese ID wird bei deiner Instanz wahrscheinlich nicht stimmen, und endet dann in dem Fehler.

**Comment by GreenPepperYT** [comment]
Hi, habe nun den Code geändert und es funktioniert immer noch nicht, der gleiche Fehler.

Zudem es ja beim Redhost Panel funktioniert, wo die ID auch auf 1 ist..

**Comment by BSchleyer** [comment]
Ein User und ich haben das Problem gestern bereits schon identifiziert und konnten es bei Ihm lösen.

Das ist ein simples Problem:
- Abgleich der Function mit den EGG-ID's direkt aus Pterodactyl
- Abgleich der ID's, im Frontend und Backend der Bestellfiles

Wenn das gemacht wurde, sollte es zu keinem Problem mehr kommen. Sollte der Abgleich nicht stimmen ,dementsprechend abändern und erneut versuchen.

Andernfalls im Discord via DM melden.
Tag: Björn Schleyer#5384

**Comment by GreenPepperYT** [comment]
Ich nehme an mit 
"Abgleich der Function mit den EGG-ID's direkt aus Pterodactyl" meinst du ich solle die createServer Function mit der richtigen Egg-ID aus Pterodactyl tauschen?
und was meinst du mit den zweiten Punkt?
